version: "3"
services:
  mongo:
    container_name: rampmongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"

  app:
    container_name: rampapi
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - ${PORT}:3000
    links:
      - mongo